services:
  backend:
    build:
      context: ./backend
    container_name: trackroute-backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: file:./data/dev.db
      CORS_ORIGIN: http://localhost
      FEATURE_ROUTES_READ: "true"
      FEATURE_ROUTES_CREATE: "true"
      FEATURE_ROUTES_SEED: "false"
      FEATURE_ROUTES_UPDATE_ENABLED: "true"
      FEATURE_ROUTES_SOFT_DELETE_ENABLED: "true"
      FEATURE_TRACKING_ENABLED: "true"
      FEATURE_SOAP_CACHE_ENABLED: "true"
      FEATURE_SOAP_STUB_ENABLED: "true"
      TRACKING_PROVIDER: stub
      SOAP_TRACKING_URL: http://localhost:4001/mock-soap/tracking
      SOAP_TRACKING_TIMEOUT_MS: 5000
    volumes:
      - trackroute_prisma_data:/app/prisma/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: trackroute-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  trackroute_prisma_data:
